{{- range $name, $config := .Values.services }}
{{- if ne $name "worker" }}
{{- $fullName := printf "%s-%s" $.Release.Name $name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "voting-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "voting-app.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
---
{{- end }}
{{- end }}
